# Add project specific ProGuard rules here.
# By default, the flags in this file are applied to
# all build types.

# Hilt
-keep class dagger.hilt.internal.aggregatedroot.codegen.*
-keep class com.hereliesaz.lexorcist.di.*
-keep @dagger.hilt.InstallIn class *
-keep @dagger.hilt.components.SingletonComponent class *
-keep @dagger.hilt.android.HiltAndroidApp class *

# Coroutines
-keepclassmembers class kotlinx.coroutines.internal.MainDispatcherFactory {
    public static final kotlinx.coroutines.MainCoroutineDispatcher a;
}

# Data models
-keep class com.hereliesaz.lexorcist.model.** { *; }
-keep class com.hereliesaz.lexorcist.data.** { *; }

# Keep serialization classes
-keep class kotlinx.serialization.** { *; }
-keep class * implements kotlinx.serialization.Serializer { *; }
-keep class * extends kotlinx.serialization.internal.EnumSerializer { *; }

# For Gson
-keep class com.google.gson.** { *; }

# For Retrofit (used by Google API services)
-keep class retrofit2.** { *; }
-keep class com.google.api.services.** { *; }

# For MediaPipe
-keep class com.google.mediapipe.** { *; }

# Keep Hilt DI subpackages (qualifiers, generated modules), not just the top level.
-keep class com.hereliesaz.lexorcist.di.** { *; }

# Mozilla Rhino — the scripting engine reflects over its own classes at runtime.
-keep class org.mozilla.javascript.** { *; }
-dontwarn org.mozilla.javascript.**

# Apache POI (XLSX read/write) — heavy reflection + optional deps.
-keep class org.apache.poi.** { *; }
-keep class org.openxmlformats.** { *; }
-keep class org.apache.xmlbeans.** { *; }
-keep class schemaorg_apache_xmlbeans.** { *; }
-dontwarn org.apache.poi.**
-dontwarn org.openxmlformats.**
-dontwarn org.apache.xmlbeans.**

# iText (PDF generation).
-keep class com.itextpdf.** { *; }
-dontwarn com.itextpdf.**

# Google API client (models are accessed reflectively by the JSON parser).
-keep class com.google.api.client.** { *; }
-keep class com.google.api.** { *; }
-dontwarn com.google.api.client.**

# gRPC (used transitively by Google/Firebase clients).
-keep class io.grpc.** { *; }
-dontwarn io.grpc.**

# Microsoft MSAL / identity (OneDrive auth — disabled but still linked).
-keep class com.microsoft.identity.** { *; }
-dontwarn com.microsoft.identity.**
-dontwarn com.microsoft.graph.**

# Dropbox SDK.
-keep class com.dropbox.** { *; }
-dontwarn com.dropbox.**

# Jakarta Mail (IMAP).
-keep class jakarta.mail.** { *; }
-keep class com.sun.mail.** { *; }
-dontwarn jakarta.mail.**
-dontwarn com.sun.mail.**

# Vosk speech-to-text (JNI bindings).
-keep class org.vosk.** { *; }
-dontwarn org.vosk.**

# TensorFlow Lite / AI Edge runtime.
-keep class org.tensorflow.** { *; }
-keep class com.google.ai.edge.** { *; }
-dontwarn org.tensorflow.**

# Keep annotated model fields used by reflective (de)serialization.
-keepattributes Signature, *Annotation*, InnerClasses, EnclosingMethod

# ---------------------------------------------------------------------------
# Missing classes referenced by desktop/server JVM libraries that this app
# pulls in transitively but never executes: Apache POI's AWT rendering paths,
# log4j and its OSGi annotations, Woodstox/StAX, Micrometer and Reactor (via
# the Microsoft Graph SDK), MediaPipe's optional profiling protos, and
# AutoValue's javapoet copy which references javax.lang.model.
#
# Generated by AGP into app/build/outputs/mapping/release/missing_rules.txt.
# Without these R8 fails the release build outright, which is one reason no
# release build has succeeded. Regenerate from that file after a dependency
# change rather than editing by hand.
# ---------------------------------------------------------------------------
-dontwarn aQute.bnd.annotation.baseline.BaselineIgnore
-dontwarn aQute.bnd.annotation.spi.ServiceConsumer
-dontwarn aQute.bnd.annotation.spi.ServiceProvider
-dontwarn com.github.luben.zstd.ZstdInputStream
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate
-dontwarn io.micrometer.context.ContextAccessor
-dontwarn java.awt.Shape
-dontwarn javax.lang.model.SourceVersion
-dontwarn javax.lang.model.element.Element
-dontwarn javax.lang.model.element.ElementKind
-dontwarn javax.lang.model.element.Modifier
-dontwarn javax.lang.model.type.TypeMirror
-dontwarn javax.lang.model.type.TypeVisitor
-dontwarn javax.lang.model.util.SimpleTypeVisitor8
-dontwarn javax.naming.InvalidNameException
-dontwarn javax.naming.NamingException
-dontwarn javax.naming.directory.Attribute
-dontwarn javax.naming.directory.Attributes
-dontwarn javax.naming.ldap.LdapName
-dontwarn javax.naming.ldap.Rdn
-dontwarn javax.xml.crypto.Data
-dontwarn javax.xml.crypto.NodeSetData
-dontwarn javax.xml.crypto.XMLCryptoContext
-dontwarn javax.xml.crypto.XMLStructure
-dontwarn javax.xml.crypto.dom.DOMURIReference
-dontwarn javax.xml.crypto.dsig.CanonicalizationMethod
-dontwarn javax.xml.crypto.dsig.Reference
-dontwarn javax.xml.crypto.dsig.SignedInfo
-dontwarn javax.xml.crypto.dsig.XMLSignContext
-dontwarn javax.xml.crypto.dsig.keyinfo.KeyInfo
-dontwarn org.ietf.jgss.GSSContext
-dontwarn org.ietf.jgss.GSSCredential
-dontwarn org.ietf.jgss.GSSException
-dontwarn org.ietf.jgss.GSSManager
-dontwarn org.ietf.jgss.GSSName
-dontwarn org.ietf.jgss.Oid
-dontwarn org.osgi.framework.Bundle
-dontwarn org.osgi.framework.BundleContext
-dontwarn org.osgi.framework.FrameworkUtil
-dontwarn org.osgi.framework.ServiceReference
-dontwarn org.osgi.framework.wiring.BundleRevision
-dontwarn org.tukaani.xz.MemoryLimitException
-dontwarn org.tukaani.xz.SingleXZInputStream
-dontwarn org.tukaani.xz.XZInputStream
-dontwarn reactor.blockhound.integration.BlockHoundIntegration
