package com.hereliesaz.lexorcist.data

import android.os.Parcelable
import androidx.compose.runtime.Immutable
import kotlinx.parcelize.Parcelize

/**
 * Represents a logical grouping of evidence, typically corresponding to a legal exhibit.
 *
 * Marked as [Immutable] to ensure stability in Jetpack Compose.
 * The [evidenceIds] list is treated as a stable property, preventing unnecessary recompositions
 * in UI components like `ExhibitItem` when the list reference remains the same.
 */
@Immutable
@Parcelize
data class Exhibit(
    /** Unique identifier for the exhibit (auto-generated by Room). */
    val id: Int = 0,
    /** The ID of the [Case] this exhibit belongs to. */
    val caseId: Long,
    /** The display name of the exhibit (e.g., "Exhibit A"). */
    val name: String,
    /** A brief description of the exhibit's contents or relevance. */
    val description: String,
    /** A list of [Evidence.id]s associated with this exhibit. */
    val evidenceIds: List<Int>
) : Parcelable
